"""add blocks and remaining tables

Revision ID: 6759dc4f4f3c
Revises: 774198a3ed65
Create Date: 2026-03-10 12:10:30.372270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6759dc4f4f3c'
down_revision: Union[str, None] = '774198a3ed65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocks',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('parent_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('block_type', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sync_id', sa.String(length=36), nullable=False),
    sa.Column('sync_version', sa.Integer(), nullable=False),
    sa.Column('local_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['blocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_id', 'name', name='uq_block_parent_name')
    )
    op.create_index(op.f('ix_blocks_device_id'), 'blocks', ['device_id'], unique=False)
    op.create_index(op.f('ix_blocks_is_deleted'), 'blocks', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_blocks_parent_id'), 'blocks', ['parent_id'], unique=False)
    op.create_index('ix_blocks_parent_position', 'blocks', ['parent_id', 'position'], unique=False)
    op.create_index('ix_blocks_path', 'blocks', ['path'], unique=False)
    op.create_index(op.f('ix_blocks_sync_id'), 'blocks', ['sync_id'], unique=True)
    op.create_index('ix_blocks_type', 'blocks', ['block_type'], unique=False)
    op.create_table('block_contents',
    sa.Column('block_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sync_id', sa.String(length=36), nullable=False),
    sa.Column('sync_version', sa.Integer(), nullable=False),
    sa.Column('local_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_block_contents_block_id'), 'block_contents', ['block_id'], unique=False)
    op.create_index('ix_block_contents_block_position', 'block_contents', ['block_id', 'position'], unique=False)
    op.create_index(op.f('ix_block_contents_device_id'), 'block_contents', ['device_id'], unique=False)
    op.create_index(op.f('ix_block_contents_is_deleted'), 'block_contents', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_block_contents_sync_id'), 'block_contents', ['sync_id'], unique=True)
    op.create_table('block_entries',
    sa.Column('block_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sync_id', sa.String(length=36), nullable=False),
    sa.Column('sync_version', sa.Integer(), nullable=False),
    sa.Column('local_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_block_entries_block_archived', 'block_entries', ['block_id', 'is_archived'], unique=False)
    op.create_index(op.f('ix_block_entries_block_id'), 'block_entries', ['block_id'], unique=False)
    op.create_index('ix_block_entries_data', 'block_entries', ['data'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_block_entries_device_id'), 'block_entries', ['device_id'], unique=False)
    op.create_index(op.f('ix_block_entries_is_deleted'), 'block_entries', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_block_entries_sync_id'), 'block_entries', ['sync_id'], unique=True)
    op.create_table('block_fields',
    sa.Column('block_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('field_type', sa.String(length=50), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('default_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sync_id', sa.String(length=36), nullable=False),
    sa.Column('sync_version', sa.Integer(), nullable=False),
    sa.Column('local_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('block_id', 'name', name='uq_field_block_name')
    )
    op.create_index(op.f('ix_block_fields_block_id'), 'block_fields', ['block_id'], unique=False)
    op.create_index('ix_block_fields_block_position', 'block_fields', ['block_id', 'position'], unique=False)
    op.create_index(op.f('ix_block_fields_device_id'), 'block_fields', ['device_id'], unique=False)
    op.create_index(op.f('ix_block_fields_is_deleted'), 'block_fields', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_block_fields_sync_id'), 'block_fields', ['sync_id'], unique=True)
    op.create_table('triggers',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('condition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('action_params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('block_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sync_id', sa.String(length=36), nullable=False),
    sa.Column('sync_version', sa.Integer(), nullable=False),
    sa.Column('local_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_triggers_block_id'), 'triggers', ['block_id'], unique=False)
    op.create_index(op.f('ix_triggers_device_id'), 'triggers', ['device_id'], unique=False)
    op.create_index(op.f('ix_triggers_event_type'), 'triggers', ['event_type'], unique=False)
    op.create_index(op.f('ix_triggers_is_active'), 'triggers', ['is_active'], unique=False)
    op.create_index(op.f('ix_triggers_is_deleted'), 'triggers', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_triggers_sync_id'), 'triggers', ['sync_id'], unique=True)
    # NOTE: Skipped auto-detected index renames and enum type changes
    # for existing tables (conversation_messages, devices, plans, users)
    # as they are cosmetic and the VARCHAR status columns work correctly.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_triggers_sync_id'), table_name='triggers')
    op.drop_index(op.f('ix_triggers_is_deleted'), table_name='triggers')
    op.drop_index(op.f('ix_triggers_is_active'), table_name='triggers')
    op.drop_index(op.f('ix_triggers_event_type'), table_name='triggers')
    op.drop_index(op.f('ix_triggers_device_id'), table_name='triggers')
    op.drop_index(op.f('ix_triggers_block_id'), table_name='triggers')
    op.drop_table('triggers')
    op.drop_index(op.f('ix_block_fields_sync_id'), table_name='block_fields')
    op.drop_index(op.f('ix_block_fields_is_deleted'), table_name='block_fields')
    op.drop_index(op.f('ix_block_fields_device_id'), table_name='block_fields')
    op.drop_index('ix_block_fields_block_position', table_name='block_fields')
    op.drop_index(op.f('ix_block_fields_block_id'), table_name='block_fields')
    op.drop_table('block_fields')
    op.drop_index(op.f('ix_block_entries_sync_id'), table_name='block_entries')
    op.drop_index(op.f('ix_block_entries_is_deleted'), table_name='block_entries')
    op.drop_index(op.f('ix_block_entries_device_id'), table_name='block_entries')
    op.drop_index('ix_block_entries_data', table_name='block_entries', postgresql_using='gin')
    op.drop_index(op.f('ix_block_entries_block_id'), table_name='block_entries')
    op.drop_index('ix_block_entries_block_archived', table_name='block_entries')
    op.drop_table('block_entries')
    op.drop_index(op.f('ix_block_contents_sync_id'), table_name='block_contents')
    op.drop_index(op.f('ix_block_contents_is_deleted'), table_name='block_contents')
    op.drop_index(op.f('ix_block_contents_device_id'), table_name='block_contents')
    op.drop_index('ix_block_contents_block_position', table_name='block_contents')
    op.drop_index(op.f('ix_block_contents_block_id'), table_name='block_contents')
    op.drop_table('block_contents')
    op.drop_index('ix_blocks_type', table_name='blocks')
    op.drop_index(op.f('ix_blocks_sync_id'), table_name='blocks')
    op.drop_index('ix_blocks_path', table_name='blocks')
    op.drop_index('ix_blocks_parent_position', table_name='blocks')
    op.drop_index(op.f('ix_blocks_parent_id'), table_name='blocks')
    op.drop_index(op.f('ix_blocks_is_deleted'), table_name='blocks')
    op.drop_index(op.f('ix_blocks_device_id'), table_name='blocks')
    op.drop_table('blocks')
    # ### end Alembic commands ###
